Fix T & ArrayWrapper1D::operator[](int index)
With MinGW I get the following error, because constexpr clashes with const:
vulkan.hpp:544:30: error: ‘constexpr T& vk::ArrayWrapper1D<T, N>::operator[](int) const’
cannot be overloaded with ‘constexpr const T& vk::ArrayWrapper1D<T, N>::operator[](int) const’
  544 |     VULKAN_HPP_CONSTEXPR T & operator[](int index) VULKAN_HPP_NOEXCEPT